### ISSUE TITLE
Too many connections on the rest server

### ISSUE THREAD

**Issue by dlsdioquino** [cristal-ise/cristal-ise#149]
Database connections would still persist on the database even if the user's cookie has expired or if they close their browsers.
The database connection that persists would sometimes max out the available connections the postgresql database have and throw a `Too many clients already exception` in the Rest SERVER.

**Comment by romejoseph** [comment]
Created an automated test, 300 login-logout, on Issue149_Too_many_connections branch of TitusTech/hmws.

**Comment by taurus227** [comment]
#161 merged
https://github.com/cristal-ise/cristal-ise/pull/161/files#diff-a7a816850ae16137ec1671784b3f7233L172
is a quick fix for this problem, instead of creating a connection using `DriverManager.getConnection(uri, user, pwd)` and then transferring this connection to jOOQ `DSL.using(connection)`, we let the jOOQ `DSL.using(uri, user, pwd)` create its own connection, which will also allow the `DSLContext.close()` to close it.

The ultimate solution would be to use a connection pool, see https://github.com/cristal-ise/cristal-ise/issues/43 and also https://github.com/cristal-ise/cristal-ise/issues/22

**Comment by dlsdioquino** [comment]
Issue tested. I ran a script connecting to the /scriptResult endpoint. 
Previous behavior is that it added a connection when we use the query `select count(*) from pg_stat_activity`.
Now it closes its connection after the request has been fulfilled after sending each query
